Repository AY2223S2-CS2103-F11-2/tp, pull requests merged in 2023-03, with the labels that each got.

#40 Update c0j0s info in aboutus
  docs/AboutUs.md
Labels: documentation

#39 Standardise use case formats
  docs/DeveloperGuide.md
Labels: documentation

#55 Add delivery jobs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  src/main/java/seedu/address/model/ReadOnlyDeliveries.java
  src/main/java/seedu/address/model/deliveryjobs/Customer.java
  src/main/java/seedu/address/model/deliveryjobs/DeliveryJob.java
  src/main/java/seedu/address/model/deliveryjobs/DeliveryTime.java
  src/main/java/seedu/address/model/deliveryjobs/Earning.java
  src/main/java/seedu/address/model/deliveryjobs/ID.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/DeliveryMan.java
Labels: enhancement

#57 Delete chat function, update UG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/c0j0s.md
  src/main/resources/view/PersonListCard.fxml
Labels: enhancement

#77 Add job list view to main window
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/job/DeliveryJobCard.java
  src/main/java/seedu/address/ui/job/DeliveryJobListPanel.java
  src/main/java/seedu/address/ui/main/CommandBox.java
  src/main/java/seedu/address/ui/main/ResultDisplay.java
  src/main/java/seedu/address/ui/main/StatusBarFooter.java
  src/main/java/seedu/address/ui/person/PersonCard.java
  src/main/java/seedu/address/ui/person/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DeliveryJobListCard.fxml
  src/main/resources/view/DeliveryJobListPanel.fxml
  src/main/resources/view/MainWindow-old.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsWindow.css
Labels: enhancement

#84 Add sender to delivery job model
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
  src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java
Labels: enhancement

#95 Add person id to person model
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/person/AddCommand.java
  src/main/java/seedu/address/logic/commands/person/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/person/EditCommand.java
  src/main/java/seedu/address/logic/commands/person/FindCommand.java
  src/main/java/seedu/address/logic/commands/person/ListCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
  src/main/java/seedu/address/logic/parser/person/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/person/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/person/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/person/FindCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/Earning.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
  src/main/java/seedu/address/storage/json/model/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/job/DeliveryJobCard.java
  src/main/java/seedu/address/ui/job/DeliveryJobDetailPane.java
  src/main/java/seedu/address/ui/job/DeliveryJobFullDetail.java
  src/main/java/seedu/address/ui/job/DeliveryJobListPanel.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java
Labels: enhancement

#103 Add delivery date attribute to model
  src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobs/DeliveryDate.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliverySlot.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobCard.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobFullDetail.java
  src/main/resources/view/DeliveryJobListCard.fxml
  src/main/resources/view/FullDeliveryJobDetailPane.fxml
  src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java
Labels: enhancement

#104 Fix DG formatting
  docs/DeveloperGuide.md
Labels: documentation

#116 Add sorting method to sort job list based on date and slot
  src/main/java/seedu/address/logic/commands/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/TimetableDateCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobs/DeliveryDate.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliveryList.java
  src/main/java/seedu/address/model/jobs/DeliverySlot.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyTime.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/DayJobListPanel.java
  src/main/resources/view/DayJobListPanel.fxml
  src/main/resources/view/TimetableWindow.fxml
Labels: type.Timetable, type.Logic

#118 Notification of reminders can show at every clock hour.
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/ListReminderCommand.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
  src/main/java/seedu/address/logic/parser/reminder/DeleteReminderParser.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/notification/BackgroundNotificationScheduler.java
  src/main/java/seedu/address/ui/notification/BackgroundReminderTask.java
  src/main/java/seedu/address/ui/notification/NotificationManager.java
Labels: enhancement

#130 Update DG draft for stats window
  docs/DeveloperGuide.md
Labels: documentation

#128 Update DG and timetable window
  docs/DeveloperGuide.md
  docs/diagrams/TimetableDateSequenceDiagram.puml
  docs/diagrams/TimetableSequenceDiagram.puml
  docs/images/TimetableDateSequenceDiagram.png
  docs/images/TimetableSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/DayDeliveryJobCard.java
  src/main/java/seedu/address/ui/jobs/DayJobListPanel.java
  src/main/resources/view/DayDeliveryJobListCard.fxml
Labels: documentation

#131 Add access to address book
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/java/seedu/address/ui/person/PersonCard.java
  src/main/java/seedu/address/ui/person/PersonListPanel.java
  src/main/resources/view/AddressBookWIndow.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow-old.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#132 Extend execute in logic to accept command as arg
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
Labels: enhancement

#133 Add support for set job as not/ complete
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
  src/main/java/seedu/address/logic/parser/jobs/CompleteDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/resources/view/MainWindow.fxml
Labels: enhancement

#138 Fix UI in Timetable Window
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/TimetableDateCommand.java
  src/main/java/seedu/address/logic/parser/timetable/TimetableParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TimetableDetailPanel.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/DayJobListPanel.java
  src/main/java/seedu/address/ui/timetable/DayOfMonthPanel.java
  src/main/java/seedu/address/ui/timetable/DayOfWeekPanel.java
  src/main/java/seedu/address/ui/timetable/WeekJobListPanel.java
  src/main/resources/view/AddressBookWIndow.fxml
  src/main/resources/view/DayDeliveryJobListCard.fxml
  src/main/resources/view/DayJobListPane.fxml
  src/main/resources/view/DayJobListPanel.fxml
  src/main/resources/view/DayOfMonthPanel.fxml
  src/main/resources/view/DayOfWeekPanel.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListCard.fxml
  src/main/resources/view/DeliveryJobListPanel.fxml
  src/main/resources/view/FullDeliveryJobDetailPane.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ReminderListWindow.fxml
  src/main/resources/view/TimetablePanel.fxml
  src/main/resources/view/TimetableWindow.fxml
  src/main/resources/view/WeekJobListPanel.fxml
Labels: type.Ui, function.Timetable

#142 Refine detail pane in main window
  docs/images/Ui.png
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliverySlot.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobCard.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/testutil/TypicalDeliveryJobs.java
Labels: enhancement, type.Ui

#137 Add implementation details for Notification feature
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/NotificationSequenceDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/NotificationSequenceDiagram.png
  docs/team/c0j0s.md
  docs/team/chinjunan.md
Labels: documentation

#148 Fix repeating job bug in timetable window
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableDateCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableUnscheduleCommand.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/logic/parser/timetable/TimetableDateCommandParser.java
  src/main/java/seedu/address/logic/parser/timetable/TimetableParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/DayDeliveryJobCard.java
  src/main/java/seedu/address/ui/jobs/DayJobListPanel.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/java/seedu/address/ui/timetable/TimetableDetailPanel.java
  src/main/java/seedu/address/ui/timetable/UnscheduleWindow.java
  src/main/java/seedu/address/ui/timetable/WeekJobListPanel.java
  src/main/resources/view/DayDeliveryJobListCard.fxml
  src/main/resources/view/DayJobListPane.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UnscheduleWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug, type.Logic, severity.High

#152 Add Total Earnings to stats window
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/stats/TotalEarnings.java
  src/main/java/seedu/address/model/stats/TotalJobs.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
Labels: enhancement

#156 [AddJobWindow] Refine optional job schedule validation logic
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/resources/view/AddDeliveryJobWindow.fxml
  src/main/resources/view/DayDeliveryJobListCard.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListCard.fxml
  src/main/resources/view/MainWindow copy.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/UnscheduleWindow.fxml
Labels: type.Bug, type.Ui

#159 Update add_job command: Make delivery date, slot, earning optional
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableCompletedCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableDateCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableUnscheduleCommand.java
  src/main/java/seedu/address/logic/parser/jobs/AddDeliveryJobCommandParser.java
  src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/Earning.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyTimeAndEarn.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/notification/NotificationManager.java
Labels: type.Logic, function.MainWindow

#163 Add support to sort and filter job list
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyDeliveries.java
  src/main/java/seedu/address/model/deliveryjobs/Customer.java
  src/main/java/seedu/address/model/deliveryjobs/DeliveryJob.java
  src/main/java/seedu/address/model/deliveryjobs/DeliveryTime.java
  src/main/java/seedu/address/model/deliveryjobs/Earning.java
  src/main/java/seedu/address/model/deliveryjobs/ID.java
  src/main/java/seedu/address/model/jobs/DeliverySlot.java
  src/main/java/seedu/address/model/jobs/Earning.java
  src/main/java/seedu/address/model/jobs/sorters/DeliveryFilterOption.java
  src/main/java/seedu/address/model/jobs/sorters/DeliverySortOption.java
  src/main/java/seedu/address/model/jobs/sorters/OrderedSorter.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyDate.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyDelivered.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyEarning.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobFullDetail.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/resources/view/AddDeliveryJobWindow.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListPanel.fxml
  src/main/resources/view/MainWindow copy.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement, type.Ui

#164 Hide sort/filter options when no handler is set
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/resources/view/DeliveryJobListPanel.fxml
Labels: type.Ui

#170 Fix issue with opening duplicate create job window
  src/main/java/seedu/address/model/jobs/DeliverySlot.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/resources/view/AddDeliveryJobWindow.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListPanel.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
Labels: type.Bug, type.Ui

#178 Change timetable window to dark theme
  src/main/java/seedu/address/Main.java
  src/main/java/seedu/address/storage/json/model/JsonAdaptedDeliveryJob.java
  src/main/java/seedu/address/ui/jobs/DayDeliveryJobCard.java
  src/main/java/seedu/address/ui/timetable/DayJobListPanel.java
  src/main/java/seedu/address/ui/timetable/DayOfMonthPanel.java
  src/main/java/seedu/address/ui/timetable/DayOfWeekPanel.java
  src/main/java/seedu/address/ui/timetable/TimetableDetailPanel.java
  src/main/resources/view/AddDeliveryJobWindow.fxml
  src/main/resources/view/DayDeliveryJobListCard.fxml
  src/main/resources/view/DayJobListPane.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
  src/main/resources/view/DeliveryJobListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/TimetablePanel.fxml
  src/main/resources/view/TimetableWindow.fxml
Labels: type.Ui, function.Timetable

#179 Fix issue with null input in add job window
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
Labels: type.Bug

#180 Mass import feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/jobs/ImportDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/jobs/ImportDeliveryJobCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsWindow.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/main/CommandBox.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: enhancement

#187 Add delete button and command group filtering for logic
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandGroup.java
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/DeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/ImportDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/person/AddCommand.java
  src/main/java/seedu/address/logic/commands/person/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/person/EditCommand.java
  src/main/java/seedu/address/logic/commands/person/FindCommand.java
  src/main/java/seedu/address/logic/commands/person/ListCommand.java
  src/main/java/seedu/address/logic/commands/person/PersonCommand.java
  src/main/java/seedu/address/logic/parser/jobs/ImportDeliveryJobCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/resources/view/DeliveryJobDetailPane.fxml
Labels: type.Bug, enhancement, type.Ui

#188 Add feedback for sort, filter action and detail pane.
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/jobs/DeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/person/ListCommand.java
  src/main/java/seedu/address/logic/commands/person/PersonCommand.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
  src/main/resources/view/AddDeliveryJobWindow.fxml
  src/main/resources/view/DeliveryJobDetailPane.fxml
Labels: type.Bug

#193 Add feedback for find_job command
  src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/person/PersonCard.java
Labels: type.Bug

#192 Massfix2
  src/main/java/seedu/address/logic/commands/jobs/ImportDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/jobs/ImportDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
Labels: enhancement

#195 Chain find_job command predicates for and logic
  src/main/java/seedu/address/logic/commands/CommandGroup.java
  src/main/java/seedu/address/logic/commands/StatisticsCommand.java
  src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/ListReminderCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableCompletedCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableDateCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableUnscheduleCommand.java
  src/main/java/seedu/address/logic/parser/jobs/FindDeliveryJobCommandParser.java
  src/main/java/seedu/address/model/jobs/DeliveryJob.java
  src/main/java/seedu/address/model/jobs/DeliveryJobContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsDeliveryDatePredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsDeliverySlotPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsEarningPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsJobIdPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsRecipientIdPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsSenderIdPredicate.java
  src/main/java/seedu/address/model/jobs/predicate/DeliveryJobContainsStatusPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/AddressBookWIndow.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/person/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/person/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/person/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#196 Update UG
  docs/UserGuide.md
Labels: documentation

#197 Add optional args for edit cmd
  src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/jobs/DeleteDeliveryJobCommandParser.java
  src/main/java/seedu/address/logic/parser/jobs/EditDeliveryJobCommandParser.java
Labels: type.Bug

#199 Add images to UG
  docs/UserGuide.md
  docs/images/Addjob.png
  docs/images/Completedjobs.png
  docs/images/Dukedeliveryaddressbook.png
  docs/images/Inputcommands.png
  docs/images/Timetable.png
  docs/images/Unscheduledjobs.png
Labels: documentation

#202 Fix fxml file URL in AddressBookWindow
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/ui/person/AddressBookWindow.java
Labels: type.Bug

#203 update command guides and implementation details
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditDeliveryJobSequenceDiagram.puml
  docs/images/EditDeliveryJobSequenceDiagram.png
  docs/images/Ui.png
  docs/images/addressbookEntry.png
  docs/images/comJob.png
  docs/images/delJob.png
  docs/images/editJob.png
  docs/images/listJob.png
  docs/images/listJobSortFilter.png
  docs/index.md
Labels: documentation

#204 Update UG
  docs/UserGuide.md
  docs/images/Checked.png
  docs/images/Timetable.png
  docs/images/completebutton.png
  docs/images/deletebutton.png
  docs/images/penbutton.png
  docs/index.md
Labels: documentation
