Repository AY2223S2-CS2103-F11-2/tp, pull requests merged in 2023-04, with the labels that each got.

#207 Patch clear command to person
  src/main/java/seedu/address/logic/commands/person/ClearCommand.java
  src/main/java/seedu/address/logic/parser/DukeDriverParser.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobCard.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/resources/view/ModifyDeliveryJobWindow.fxml
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/person/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Bug

#248 Notification fix
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReminderListWindow.java
  src/main/java/seedu/address/ui/notification/BackgroundNotificationScheduler.java
  src/main/java/seedu/address/ui/notification/BackgroundReminderTask.java
  src/main/java/seedu/address/ui/notification/BackgroundScheduleTask.java
  src/main/java/seedu/address/ui/notification/NotificationManager.java
Labels: type.Bug

#246 Fix timetable and timetable_date bug
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/person/FindCommand.java
  src/main/java/seedu/address/logic/commands/person/ListCommand.java
  src/main/java/seedu/address/logic/commands/reminder/ListReminderCommand.java
  src/main/java/seedu/address/logic/commands/timetable/TimetableDateCommand.java
  src/main/java/seedu/address/model/person/Customer.java
  src/main/java/seedu/address/model/person/DeliveryMan.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/timetable/DayDeliveryJobCard.java
  src/main/java/seedu/address/ui/timetable/DayJobListPanel.java
  src/main/resources/view/DayDeliveryJobListCard.fxml
  src/main/resources/view/DayJobListPane.fxml
Labels: type.Bug, severity.Medium

#253 add event listener to timetable windows + fix UG bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/jobs/DeliveryDate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/TimetableWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/java/seedu/address/ui/timetable/CompleteWindow.java
  src/main/java/seedu/address/ui/timetable/TimetableDetailPanel.java
  src/main/java/seedu/address/ui/timetable/UnscheduleWindow.java
  src/main/java/seedu/address/ui/timetable/WeekJobListPanel.java
Labels: type.Bug, documentation, function.Timetable

#254 Update UG: Lock button in job detail + auto update Table of content
  docs/UserGuide.md
  docs/images/hideDetail.png
  docs/images/unhideDetail.png
Labels: type.Bug, documentation

#258 Update UG and Ha Duong PPP
  docs/UserGuide.md
  docs/images/johndoe.png
  docs/team/dohaduong.md
  src/main/java/seedu/address/logic/commands/person/ListCommand.java
  src/main/java/seedu/address/logic/parser/timetable/TimetableParser.java
  src/main/resources/view/AddressBookDialog.fxml
Labels: type.Bug, documentation

#262 Update PPP
  docs/team/zhuleyao.md
Labels: documentation

#260 Update UG
  docs/UserGuide.md
  docs/team/dohaduong.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/jobs/AddDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/logic/commands/reminder/AddReminderCommand.java
  src/main/java/seedu/address/logic/commands/reminder/DeleteReminderCommand.java
  src/main/java/seedu/address/logic/parser/reminder/AddReminderParser.java
  src/main/java/seedu/address/ui/timetable/CompleteWindow.java
  src/test/java/seedu/address/logic/commands/jobs/CompleteDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/DeleteDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/ImportDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/AddReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/DeleteReminderCommandTest.java
  src/test/java/seedu/address/logic/commands/reminder/ListReminderCommandTest.java
Labels: type.Bug, documentation

#265 Update UiPartClassDiagram + DeleteDeliveryJobSequenceDiagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/DeleteDeliveryJobSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteDeliveryJobSequenceDiagram.png
Labels: documentation

#266 Fix issue with job detail pane in main window
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommand.java
  src/main/java/seedu/address/model/jobs/DeliveryDate.java
  src/main/java/seedu/address/model/jobs/sorters/SortbyTimeAndEarn.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobDetailPane.java
  src/main/java/seedu/address/ui/jobs/DeliveryJobListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/jobs/ListDeliveryJobCommandTest.java
Labels: type.Bug

#269 Update DG ui section
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiClassDiagramCreateJob.puml
  docs/diagrams/UiClassDiagramMainWindow.puml
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagramCreateJob.png
  docs/images/UiClassDiagramMainWindow.png
  docs/team/c0j0s.md
  src/main/java/seedu/address/ui/jobs/AddDeliveryJobWindow.java
Labels: documentation

#272 Update DG and add some test cases
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/jobs/EditDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/jobs/FindDeliveryJobCommandTest.java
  src/test/java/seedu/address/logic/commands/person/AddCommandTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: documentation

#279 Fix import bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/jobs/ImportDeliveryJobCommand.java
  src/main/java/seedu/address/logic/parser/jobs/ImportDeliveryJobCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/parser/jobs/ImportDeliveryJobParserTest.java
Labels: FeatureFlaw
